task/task/urls.py
from django.contrib import admin
from django.urls import path, include
from taskapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
]

task/taskapp/urls.py
from django.urls import path
from . import views
app_name = 'taskapp'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('createTask', views.createTask, name = 'createTask'),
    path('editTask/<int:pk>', views.editTask, name = 'editTask'),
    path('viewTask/<int:pk>', views.viewTask, name = 'viewTask'),
]

task/taskapp/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
    name = models.CharField(max_length = 40)
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 400)
    link_id = models.AutoField(primary_key = True)
    datecreated = models.DateTimeField()
    datelastmodified = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.link_id:
            self.datecreated = timezone.now()
        else:
            self.datecreated = self.getCreatedDate()
        self.datelastmodified = timezone.now()
        return super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def getCreatedDate(self):
        return self.datecreated

class Comments(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 200)

    def __str__(self):
        return self.comment

task/taskapp/forms.py
from django import forms
from django.forms import (formset_factory, modelformset_factory)

from .models import Task, Comments

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name','title','description','link_id','datecreated','datelastmodified',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Name of Person to whom this task is assigned'
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the Title of the Task'
            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description of this task'
            }),
            'datecreated': forms.DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the Date when this Task created',
                'type':'date'
            }),
            'datelastmodified': forms.DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Last Modified date of the task',
                'type':'date'
            })
            
        }

class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('task','comment',)
        task_list = Task.objects.all()
        widgets = {
            'task': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the comments'
                },
                choices = task_list
            ),
            'comment': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the comments'
            })
        }

task/taskapp/views.py
from django.shortcuts import render,redirect
from .models import Task,Comments
from .forms import TaskForm, CommentsForm
# Create your views here.
def index(request):
    tasklist = Task.objects.all()
    context = {'tasklist': tasklist}
    return render(request, 'taskapp/index.html', context)

def createTask(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect('taskapp:index')
        else:
            print('form is not valid',form)
    else:
        form = TaskForm(request.GET or None)
    return render(request, 'taskapp/create_task.html',{'form': form})

def editTask(request,pk):
    task = Task.objects.get(pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance = task)
        datecreated = task.datecreated
        form.datecreated = datecreated
        print(form)
        if form.is_valid():
            task = form.save()
            return redirect('taskapp:index')
        else:
            print('form is not valid',form)
    else:
        form = TaskForm(instance = task)
    return render(request, 'taskapp/create_task.html',{'form': form})

def viewTask(request,pk):
    task = Task.objects.get(pk=pk)
    comments = Comments.objects.filter(task_id=pk)
    # print(comments)
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save()
        else:
            print('form is not valid',form)
    else:
        form = CommentsForm(request.GET or None)
    return render(request, 'taskapp/view_task.html',{'task': task,'comments': comments,'form':form})

task/taskapp/templates/taskapp/create_task.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="Agro Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
        <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
        <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
        <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    
        <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    
       <style>
        #weatherWidget .currentDesc {
            color: #ffffff!important;
        }
            .traffic-chart {
                min-height: 335px;
            }
            #flotPie1  {
                height: 150px;
            }
            #flotPie1 td {
                padding:3px;
            }
            #flotPie1 table {
                top: 20px!important;
                right: -10px!important;
            }
            .chart-container {
                display: table;
                min-width: 270px ;
                text-align: left;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #flotLine5  {
                 height: 105px;
            }
    
            #flotBarChart {
                height: 150px;
            }
            #cellPaiChart{
                height: 160px;
            }
    
        </style>
    </head>
<body>

<form class="form-horizontal" method="POST">
    {% csrf_token %}

    <div class="row spacer">
        <div class="col-2">
            <label>{{form.name.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.name}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-2">
            <label>{{form.title.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.title}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-2">
            <label>{{form.description.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.description}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-2">
            <label>{{form.datecreated.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.datecreated}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-2">
            <label>{{form.datelastmodified.label}}</label>
        </div>
        <div class="col-4">
            <div class="input-group">
                {{form.datelastmodified}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </div>
    </div>
</form>


</body>
</html>

task/taskapp/templates/taskapp/index.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="Agro Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
        <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
        <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
        <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    
        <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    
       <style>
        #weatherWidget .currentDesc {
            color: #ffffff!important;
        }
            .traffic-chart {
                min-height: 335px;
            }
            #flotPie1  {
                height: 150px;
            }
            #flotPie1 td {
                padding:3px;
            }
            #flotPie1 table {
                top: 20px!important;
                right: -10px!important;
            }
            .chart-container {
                display: table;
                min-width: 270px ;
                text-align: left;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #flotLine5  {
                 height: 105px;
            }
    
            #flotBarChart {
                height: 150px;
            }
            #cellPaiChart{
                height: 160px;
            }
            h3:nth-child(odd) {
            background: rgb(214, 207, 207);
            color:rgb(43, 111, 167);
            }
        </style>
    </head>
<body>

<a class="btn btn-primary" href="{% url 'taskapp:createTask' %}">Create New Task</a>

<hr/>

{% for task in tasklist %}
{% if task.name == 'Completed Task' %}
<h3 style= "background:green; color: white;"><a  class="btn btn-primary"  href="{% url 'taskapp:viewTask' task.link_id %}">Task {{task.link_id}}</a> {{task.title}} <span style="color:bluevoilet; font-size: 15px; background:white; color:black;">({{task.datecreated}} , {{task.datelastmodified}})</span></h3>
{% else %}
 <h3><a  class="btn btn-primary"  href="{% url 'taskapp:viewTask' task.link_id %}">Task {{task.link_id}}</a> {{task.title}} <span style="color:bluevoilet; font-size: 15px; background:white;">({{task.datecreated}} , {{task.datelastmodified}})</span></h3>
{% endif %}
{% endfor %}


</body>
</html>

task/taskapp/templates/taskapp/view_task.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="Agro Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
        <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
        <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
        <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    
        <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    
       <style>
        #weatherWidget .currentDesc {
            color: #ffffff!important;
        }
            .traffic-chart {
                min-height: 335px;
            }
            #flotPie1  {
                height: 150px;
            }
            #flotPie1 td {
                padding:3px;
            }
            #flotPie1 table {
                top: 20px!important;
                right: -10px!important;
            }
            .chart-container {
                display: table;
                min-width: 270px ;
                text-align: left;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #flotLine5  {
                 height: 105px;
            }
    
            #flotBarChart {
                height: 150px;
            }
            #cellPaiChart{
                height: 160px;
            }
            label {
                font-size: 25px;
                font-weight: bold;
            }
            .col-7{
                font-size: 25px;
                width: 100%;
            }
            .spacer:nth-child(odd) {
            background: rgb(214, 207, 207);
            color:rgb(43, 111, 167);
            }
            .content{
                margin: 5% 20%;
            }
            .btn {
                margin:5px;
            }

            .btn-primary{
                float:right;
            }
      </style>
    </head>
<body>
    <a  class="btn btn-warning"  href="{% url 'taskapp:index' %}">Back </a>
    
    
    <hr/>
 
    <a  class="btn btn-primary"  href="{% url 'taskapp:editTask' task.link_id %}">Edit This Task {{task.link_id}}</a>  
    <div class= "content"> 
        <div class="row spacer">
        <div class="col-3">
            {% if task.name == 'Completed Task' %}
            <label>Task Status</label>
            {% else %}
            <label>Assigned to</label>
            {% endif %}
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.name}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Title</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.title}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Description</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.description}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Created Date</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.datecreated}}
            </div>
        </div>
    </div>
    <div class="row spacer">
        <div class="col-3">
            <label>Modified Date</label>
        </div>
        <div class="col-7">
            <div class="input-group">
                {{task.datelastmodified}}
            </div>
        </div>
    </div>
<hr/>
    <div class="row spacer" style="background: grey; color:white;">
        <div class="col-9">
            <label>Comments Below</label>
        </div>
        {% for i in comments %}
        <div class="col-9">
            <div class="input-group">
              {{forloop.counter}}.  {{i}}
            </div>
        </div>
        {% endfor %}
    </div>
    <form class="form-horizontal" method="POST">
        {% csrf_token %}
        <div class="row spacer">
            <div class="col-2">
                <label>{{form.task.label}}</label>
            </div>
            <div class="col-7">
                <div class="input-group">
                    {{form.task}}
                </div>
            </div>
        </div>
        <div class="row spacer">
            <div class="col-2">
                <label>{{form.comment.label}}</label>
            </div>
            <div class="col-7">
                <div class="input-group">
                    {{form.comment}}
                </div>
            </div>
        </div>
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-block btn-primary">Add Comment</button>
        </div>
    </div>
</form>
</div>


</body>
</html>